# Generated by Django 5.1.2 on 2024-10-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="收件人")),
                ("subject", models.CharField(max_length=200, verbose_name="主题")),
                ("body", models.TextField(verbose_name="正文")),
                (
                    "sent_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                ("sender", models.CharField(max_length=200, verbose_name="发件人")),
            ],
            options={
                "verbose_name": "邮件",
                "verbose_name_plural": "邮件",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                ("description", models.TextField(verbose_name="商品描述")),
                ("category", models.CharField(max_length=100, verbose_name="商品类别")),
                ("location", models.CharField(max_length=200, verbose_name="存放地点")),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="日租金"
                    ),
                ),
                ("available_from", models.DateField(verbose_name="可租赁开始日期")),
                (
                    "available_to",
                    models.DateField(blank=True, null=True, verbose_name="可租赁结束日期"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可租赁"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="用户名"),
                ),
                (
                    "time",
                    models.CharField(default="", max_length=50, verbose_name="登陆时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告")),
                ("description", models.TextField(verbose_name="公告描述")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="用户名"),
                ),
                (
                    "sname",
                    models.CharField(default="", max_length=50, verbose_name="真实姓名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=50, verbose_name="密码"),
                ),
                (
                    "role",
                    models.CharField(default="", max_length=50, verbose_name="角色"),
                ),
                (
                    "bio",
                    models.CharField(
                        default="", max_length=500, null=True, verbose_name="个人介绍"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="个性签名"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="英文名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        default="", max_length=200, null=True, verbose_name="头像url"
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="职业技能"
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="编号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="邮箱"),
                ),
                (
                    "sex",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="性别"
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        default="", max_length=50, null=True, verbose_name="地区"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(verbose_name="公告")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="myapp.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="租赁开始日期")),
                ("end_date", models.DateField(verbose_name="租赁结束日期")),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=50, verbose_name="租赁状态"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总租金"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.item"
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="myapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="支付日期"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        default="Pending", max_length=50, verbose_name="支付状态"
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.rental"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=0, verbose_name="评分")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="myapp.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="myapp.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="myapp.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="myapp.user",
            ),
        ),
    ]
