# Generated by Django 5.1.2 on 2024-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_favorite_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="商品链接"
            ),
        ),
    ]
